[package]
name = "renameClips"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
native-dialog = "0.6.3"
serde_json = "1.0.87"

regex = "1"
rand = "0.8.4"
